// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using T1708ENewWeb.Models;

namespace T1708ENewWeb.Migrations
{
    [DbContext(typeof(T1708ENewWebContext))]
    partial class T1708ENewWebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("T1708ENewWeb.Models.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StudentRollNumber");

                    b.Property<int>("SubjectMark");

                    b.Property<string>("SubjectName");

                    b.HasKey("Id");

                    b.HasIndex("StudentRollNumber");

                    b.ToTable("Mark");

                    b.HasData(
                        new { Id = 1, StudentRollNumber = "A001", SubjectMark = 20, SubjectName = "Java" },
                        new { Id = 2, StudentRollNumber = "A002", SubjectMark = 20, SubjectName = "C#" },
                        new { Id = 3, StudentRollNumber = "A003", SubjectMark = 20, SubjectName = "PHP" }
                    );
                });

            modelBuilder.Entity("T1708ENewWeb.Models.Student", b =>
                {
                    b.Property<string>("RollNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("Status");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("RollNumber");

                    b.ToTable("Student");

                    b.HasData(
                        new { RollNumber = "A001", CreatedAt = new DateTime(2018, 11, 7, 22, 47, 25, 431, DateTimeKind.Local), Email = "tinhgiang9898@gmail.com", FirstName = "Giang", LastName = "Tinh", Status = 0, UpdatedAt = new DateTime(2018, 11, 7, 22, 47, 25, 432, DateTimeKind.Local) },
                        new { RollNumber = "A002", CreatedAt = new DateTime(2018, 11, 7, 22, 47, 25, 433, DateTimeKind.Local), Email = "ly@gmail.com", FirstName = "Huong", LastName = "Ly", Status = 0, UpdatedAt = new DateTime(2018, 11, 7, 22, 47, 25, 433, DateTimeKind.Local) },
                        new { RollNumber = "A003", CreatedAt = new DateTime(2018, 11, 7, 22, 47, 25, 433, DateTimeKind.Local), Email = "thanhtung@gmail.com", FirstName = "Thanh", LastName = "Tung", Status = 0, UpdatedAt = new DateTime(2018, 11, 7, 22, 47, 25, 433, DateTimeKind.Local) }
                    );
                });

            modelBuilder.Entity("T1708ENewWeb.Models.Mark", b =>
                {
                    b.HasOne("T1708ENewWeb.Models.Student", "Student")
                        .WithMany("Marks")
                        .HasForeignKey("StudentRollNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
